spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/timedeal
    username: root
    password: 32518458
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      show_sql: true
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database-platform: MySQL
logging:
  level:
    #    org.hibernate.sql: debug
    org.hibernate.sql: info
    org.hibernate.jdbc.bind: trace
server:
  port: 9060
