spring:
  datasource:
    url: jdbc:mariadb://db:3306/timedeal
    username: root
    password: 32518458
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:


    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      show_sql: true
      hibernate:
        globally_quoted_identifiers: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    database-platform: MariaDB
logging:
  level:
    #    org.hibernate.sql: debug
    org.hibernate.sql: info
    org.hibernate.jdbc.bind: trace
